root_name = 'Leap_Root'
framerate = 0.01875222
#channels = ['Xposition', 'Yposition', 'Zposition', 'Zrotation', 'Xrotation', 'Yrotation']
#bone_context = ['Brekel_Pro_Hands', 'LeftHand', 'LeftHandThumb1', 'LeftHandThumb2', 'LeftHandThumb3']
# 'offsets': [0.0, -26.7, 0.0]}}

#TODO: channels, offsets
skeleton = \
 {'Leap_Root': {'channels': ['Xposition', 'Yposition', 'Zposition', 'Zrotation', 'Xrotation', 'Yrotation'], 'children': [
#     'LeftHand',
     'RightHand'], 'parent': None},
# 'LeftHand': {'channels': ['Xposition', 'Yposition', 'Zposition', 'Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandThumb1', 'LeftHandIndex1', 'LeftHandMiddle1', 'LeftHandRing1', 'LeftHandPinky1'], 'parent': 'Brekel_Pro_Hands'},
# 'LeftHandIndex1': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandIndex2'], 'parent': 'LeftHand'},
# 'LeftHandIndex2': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandIndex3'], 'parent': 'LeftHandIndex1'},
# 'LeftHandIndex3': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandIndex3_End'], 'parent': 'LeftHandIndex2'},
# 'LeftHandIndex3_End': {'channels': [], 'children': [], 'parent': 'LeftHandIndex3'},
# 'LeftHandMiddle1': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandMiddle2'], 'parent': 'LeftHand'},
# 'LeftHandMiddle2': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandMiddle3'], 'parent': 'LeftHandMiddle1'},
# 'LeftHandMiddle3': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandMiddle3_End'], 'parent': 'LeftHandMiddle2'},
# 'LeftHandMiddle3_End': {'channels': [], 'children': [], 'parent': 'LeftHandMiddle3'},
# 'LeftHandPinky1': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandPinky2'], 'parent': 'LeftHand'},
# 'LeftHandPinky2': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandPinky3'], 'parent': 'LeftHandPinky1'},
# 'LeftHandPinky3': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandPinky3_End'], 'parent': 'LeftHandPinky2'},
# 'LeftHandPinky3_End': {'channels': [], 'children': [], 'parent': 'LeftHandPinky3'},
# 'LeftHandRing1': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandRing2'], 'parent': 'LeftHand'},
# 'LeftHandRing2': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandRing3'], 'parent': 'LeftHandRing1'},
# 'LeftHandRing3': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandRing3_End'], 'parent': 'LeftHandRing2'},
# 'LeftHandRing3_End': {'channels': [], 'children': [], 'parent': 'LeftHandRing3'},
# 'LeftHandThumb1': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandThumb2'], 'parent': 'LeftHand'},
# 'LeftHandThumb2': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandThumb3'], 'parent': 'LeftHandThumb1'},
# 'LeftHandThumb3': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['LeftHandThumb3_End'], 'parent': 'LeftHandThumb2'},
# 'LeftHandThumb3_End': {'channels': [], 'children': [], 'parent': 'LeftHandThumb3'},
'RightHand': {'channels': ['Xposition', 'Yposition', 'Zposition', 'Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandThumb2', 'RightHandIndex1', 'RightHandMiddle1', 'RightHandRing1', 'RightHandPinky1'], 'parent': 'Leap_Root'},
'RightHandIndex1': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandIndex2'], 'parent': 'RightHand'},
'RightHandIndex2': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandIndex3'], 'parent': 'RightHandIndex1'},
'RightHandIndex3': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandIndex4'], 'parent': 'RightHandIndex2'},
'RightHandIndex4': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandIndex4_End'], 'parent': 'RightHandIndex3'},
'RightHandIndex4_End': {'channels': [], 'children': [], 'parent': 'RightHandIndex4'},
'RightHandMiddle1': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandMiddle2'], 'parent': 'RightHand'},
'RightHandMiddle2': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandMiddle3'], 'parent': 'RightHandMiddle1'},
'RightHandMiddle3': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandMiddle4'], 'parent': 'RightHandMiddle2'},
'RightHandMiddle4': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandMiddle4_End'], 'parent': 'RightHandMiddle3'},
'RightHandMiddle4_End': {'channels': [], 'children': [], 'parent': 'RightHandMiddle4'},
'RightHandPinky1': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandPinky2'], 'parent': 'RightHand'},
'RightHandPinky2': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandPinky3'], 'parent': 'RightHandPinky1'},
'RightHandPinky3': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandPinky4'], 'parent': 'RightHandPinky2'},
'RightHandPinky4': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandPinky4_End'], 'parent': 'RightHandPinky3'},
'RightHandPinky4_End': {'channels': [], 'children': [], 'parent': 'RightHandPinky4'},
'RightHandRing1': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandRing2'], 'parent': 'RightHand'},
'RightHandRing2': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandRing3'], 'parent': 'RightHandRing1'},
'RightHandRing3': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandRing4'], 'parent': 'RightHandRing2'},
'RightHandRing4': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandRing4_End'], 'parent': 'RightHandRing3'},
'RightHandRing4_End': {'channels': [], 'children': [], 'parent': 'RightHandRing4'},
'RightHandThumb2': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandThumb3'], 'parent': 'RightHand'},
'RightHandThumb3': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandThumb4'], 'parent': 'RightHandThumb2'},
'RightHandThumb4': {'channels': ['Zrotation', 'Xrotation', 'Yrotation'], 'children': ['RightHandThumb4_End'], 'parent': 'RightHandThumb3'},
'RightHandThumb4_End': {'channels': [], 'children': [], 'parent': 'RightHandThumb4'}}
